title: Desi Noviyanti 
logo: "/images/logo.png?raw=true" 
description: > 
   <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/desi-noviyanti/">LinkedIn</a> |
  <a href="https://github.com/desinoviyantii">GitHub</a>
  </p>
  
  <p align="justify">
    I am ...............
    <br><br>
    I am ...............
    <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 
